learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
    path('users/', include('users.urls')),
]

learning_logs/urls.py
"""Definiuje wzorce adresów URL dla learning_logs.""" 
from django.urls import path 
from . import views 


app_name = 'learning_logs' 

urlpatterns = [
 # Strona główna.
 path('', views.index, name='index'),
 path('topics/', views.topics, name='topics'),
 path('topics/(<int:topic_id>)/', views.topic, name='topic'),
 path('new_topic/', views.new_topic, name='new_topic'),
 path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
 path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""urls schemes for users app"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Topic(models.Model):
    """toppic defined by user"""
    text = models.CharField(max_length=100)
    desc = models.CharField(max_length=250, default="")
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """returns model representation in a str form"""
        return self.text

class Entry(models.Model):
    """exact info about progress in learning"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField(max_length=100)
    desc = models.TextField(default="")
    date_added = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)


    class Meta:
        verbose_name_plural = 'entries'

        
    def __str__(self):
        return self.text[:50] if len(self.text) > 50 else self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic

        fields = ['text', 'desc']
        labels = {'text':'Topic', 'desc':'Description'}


class EntryForm(forms.ModelForm):
     class Meta:
        model = Entry
        fields = ['text', 'desc']
        labels = {'text': '', 'desc':''} 
        widgets = {'text': forms.Textarea(attrs={'cols': 80}), 'desc': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required


# Create your views here.


def index(request):
    """main page for the learning_logs app"""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """render all of the topics"""
    topics = Topic.objects.order_by('date_added')
    count = len(topics)
    context = {'topics': topics, 'count':count}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """render the details about a specific topic"""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    count = len(entries)
    context = {'topic': topic, 'entries': entries, 'count': count}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """add new topic"""
    if request.method != 'POST':
        # the user did not provide any data
        form = TopicForm()
    else:
        # the user did provide some data
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topics')

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Dodanie nowego wpisu dla określonego tematu."""
    topic = Topic.objects.get(id=topic_id) 
    if request.method != 'POST': 
        # Nie przekazano żadnych danych, należy utworzyć pusty formularz.
        form = EntryForm() 
    else:
        # Przekazano dane za pomocą żądania POST, należy je przetworzyć.
        form = EntryForm(data=request.POST) 

    if form.is_valid():
        new_entry = form.save(commit=False) 
        new_entry.topic = topic 
        new_entry.owner = request.user
        new_entry.save()
        return redirect('learning_logs:topic', topic_id=topic_id) 
    # Wyświetlenie pustego formularza.

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """script that allows me to change the instide of an entry"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    entry.owner = request.user

    if request.method != 'POST':
        form = EntryForm(instance=entry)

    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.


def register(request):
    """Rejestracja nowego użytkownika."""
    if request.method != 'POST':
    # Wyświetlenie pustego formularza rejestracji użytkownika.
        form = UserCreationForm() 
    else:
    # Przetworzenie wypełnionego formularza.
        form = UserCreationForm(data=request.POST) 
        if form.is_valid(): 
            new_user = form.save() 
            # Zalogowanie użytkownika, a następnie przekierowanie go na stronę główną.
            login(request, new_user) 
            return redirect('learning_logs:index') 
    # Wyświetlenie pustego formularza.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load static %}
<link rel="stylesheet" href="{% static 'base.css' %}">

<head>
    <meta charset="utf-8">
    <title>Learning Logs</title>
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@500&display=swap" rel="stylesheet">

</head>

<html>
<body>

<div class="toolbar">
    <div class="options">
        <a href="{% url 'learning_logs:index' %}">Learning Log</a>
        <a href="{% url 'learning_logs:topics' %}">Topics</a>
    </div>
    <div class="user-login">
        {% if user.is_authenticated %} 
            <p>Witaj, {{ user.username }}.</p>
            <a href="{% url 'users:logout' %}">Wyloguj</a>
        {% else %}
            <a href="{% url 'users:register' %}">Rejestruj</a>
            <a href="{% url 'users:login' %}">Zaloguj</a>  
        {% endif %}
    </div>
</div>

{% block content %}{% endblock content %} 

</body>

</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load static %}
{% block title %}Edycja wpisu{% endblock title %}
    <link rel="stylesheet" href="{% static 'learning_logs/static/edit_entry.css' %}">
{% block content %}
<div id='all'>
<p>
    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
</p>
<p>Edycja wpisu:</p>
<form action="{% url 'learning_logs:edit_entry' entry.id %}"method='post'> 
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Zapisz zmiany</button> 
</form>
</div>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %} 
{% block content %} 
<div id="index-things">
    {% if user.is_authenticated %} 
        <h1>Witaj, {{ user.username }}.</h1>
    {% else %}
        <h1>Learning Log pomaga w monitorowaniu postępów w nauce.</h1>
    {% endif %}
</div>
{% endblock content %} 

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% block content %}
 <p>
    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
</p> 
<p>Dodaj nowy wpis:</p>
<form action="{% url 'learning_logs:new_entry' topic.id %}"method='post'> 
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>Dodaj wpis</button>
</form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% block content %}
<p>Dodaj nowy temat:</p>
<form action="{% url 'learning_logs:new_topic' %}" method='post'> 
    {% csrf_token %} 
    {{ form.as_p }} 
    <button name="submit">Dodaj temat</button> 
 </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}  

<div id='topic-and-decs'>
    <h1>
        <nobr>{{ topic }}</nobr>
    </h1>
    <h4>{{ topic.desc }}</h4>
</div>
<div id='entries'>
    <a id='add-new-entry' href="{% url 'learning_logs:new_entry' topic.id %}">Dodaj nowy wpis</a>
       
    {% for entry in entries %}
    <div class='entry'>
        <header class='entry-header'>
            <div class='entrytopic-left'>
                <h4>{{ entry.text }}</h4>
                <p>{{ entry.owner }}</p>
                <p>{{ entry.date_added|date:'d M Y H:i' }}</p>
            </div>
            <div class='entrytopic-right'>
                <a href="{% url 'learning_logs:edit_entry' entry.id %}">Edytuj</a>
            </div>
        </header>
        <div class='entry-text'>
            <p class='desc'>{{ entry.desc|linebreaks }}</p>
            {% if forloop.counter < count%}
            <hr>
            {% endif %}
        </div>
    </div>    
    {% empty %}
        <div class='entry'>
            <p>No entries have been added yet.</p>
        </div>
    {% endfor %}
</div>


{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}
<div class="topic_entries">
  <h1 id="topics_topic">Tematy</h1>
  <a href="{% url 'learning_logs:new_topic' %}">Dodaj nowy temat</a>
  {% for topic in topics %} 
  <div class="topic_entry"> 
    <a href="{% url 'learning_logs:topic' topic.id %}">
      <h3>{{ topic.text }}</h3> 
      <p>{{ topic.desc }}</p>
    </a>
    {% comment %} {%if forloop.counter < count%}
    <hr>
    {%endif%} {% endcomment %}
  </div> 
{% empty %} 
  <div>
    <h3>Nie został jeszcze dodany żaden temat.</h3>
  </div>
{% endfor %} 
</div>

{% endblock content %}